version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/api/
    ports:
      - 8080:8080
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tarot
    ports:
      - 5432:5432

